services:
  - type: web
    name: dldb-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
